name: ragna-studio-frontend

services:
  web:
    cpu_count: 1
    image: ghcr.io/hopkins385/ragna-studio-frontend:latest
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:80',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
