services:
  web:
    deploy:
      replicas: 2
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 1s
        order: start-first
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_net'
      # Common
      - 'traefik.http.services.studio-webapp.loadbalancer.server.port=80'
      # Sticky Sessions
      # - 'traefik.http.services.studio-webapp.loadbalancer.sticky=true'
      # - 'traefik.http.services.studio-webapp.loadbalancer.sticky.cookie.name=studioapp'
      # - 'traefik.http.services.studio-webapp.loadbalancer.sticky.cookie.secure=true'
      # - 'traefik.http.services.studio-webapp.loadbalancer.sticky.cookie.httpOnly=true'
      # - 'traefik.http.services.studio-webapp.loadbalancer.sticky.cookie.samesite=Strict'
      # HTTP Routers
      - 'traefik.http.routers.studio-webapp.rule=Host(`studio.ragna.io`)'
      - 'traefik.http.routers.studio-webapp.entrypoints=https'
      - 'traefik.http.routers.studio-webapp.service=studio-webapp'
      - 'traefik.http.routers.studio-webapp.middlewares=crowdsec-bouncer@file,default@file' #,gzip@file
      - 'traefik.http.routers.studio-webapp.tls=true'
      - 'traefik.http.routers.studio-webapp.tls.certresolver=http'
    networks:
      traefik_net:

networks:
  traefik_net:
    external: true
